In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("loan_approval_data.csv")

In [43]:
# df.head()
# df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Applicant_Income                 1000 non-null   float64
 1   Coapplicant_Income               1000 non-null   float64
 2   Age                              1000 non-null   float64
 3   Dependents                       1000 non-null   float64
 4   Credit_Score                     1000 non-null   float64
 5   Existing_Loans                   1000 non-null   float64
 6   DTI_Ratio                        1000 non-null   float64
 7   Savings                          1000 non-null   float64
 8   Collateral_Value                 1000 non-null   float64
 9   Loan_Amount                      1000 non-null   float64
 10  Loan_Term                        1000 non-null   float64
 11  Education_Level                  1000 non-null   int64
 12  Loan_Approved                    1000 non-null   int64
 13  Employment_Status_Salaried       1000 non-null   float64
 14  Employment_Status_Self-employed  1000 non-null   float64
 15  Employment_Status_Unemployed     1000 non-null   float64
 16  Marital_Status_Single            1000 non-null   float64
 17  Loan_Purpose_Car                 1000 non-null   float64
 18  Loan_Purpose_Education           1000 non-null   float64
 19  Loan_Purpose_Home                1000 non-null   float64
 20  Loan_Purpose_Personal            1000 non-null   float64
 21  Property_Area_Semiurban          1000 non-null   float64
 22  Property_Area_Urban              1000 non-null   float64
 23  Gender_Male                      1000 non-null   float64
 24  Employer_Category_Government     1000 non-null   float64
 25  Employer_Category_MNC            1000 non-null   float64
 26  Employer_Category_Private        1000 non-null   float64
 27  Employer_Category_Unemployed     1000 non-null   float64
 28  DTI_Ratio_sq                     1000 non-null   float64
 29  Credit_Score_sq                  1000 non-null   float64
dtypes: float64(28), int64(2)
memory usage: 234.5 KB

# Handle Missing Value

In [44]:
categorical_cols = df.select_dtypes(include=["object"]).columns
# numerical_cols = df.select_dtypes(include=["float64", "int64" ]).columns
# numerical_cols = df.select_dtypes(include=["number"]).columns
numerical_cols = df.select_dtypes(include=["float64"]).columns

In [45]:
categorical_cols.size + numerical_cols.size

28

In [46]:
from sklearn.impute import SimpleImputer

num_imp = SimpleImputer(strategy='mean')
df[numerical_cols] = num_imp.fit_transform(df[numerical_cols])

In [47]:
df.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,...,Loan_Purpose_Personal,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,DTI_Ratio_sq,Credit_Score_sq
0,17795.0,1387.0,51.0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.2809,405769.0
1,2860.0,2679.0,46.0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0900,385641.0
2,7390.0,2106.0,25.0,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0400,454276.0
3,13964.0,8173.0,40.0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0961,335241.0
4,13284.0,4223.0,31.0,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0841,519841.0

In [48]:
cat_imp = SimpleImputer(strategy='most_frequent')
df[categorical_cols] = cat_imp.fit_transform(df[categorical_cols])

ValueError: at least one array or dtype is required

In [ ]:
df.isnull().sum()

# EDA - exploratory data analysis

In [ ]:
# How balanced our classes are?

class_count = df["Loan_Approved"].value_counts()
plt.pie(class_count, labels={"No", "Yes"}, autopct="%1.1f%%")
plt.title("Is Loan approved or not?")

In [ ]:
# Analyze Categories

# gender_cnt = df["Gender"].value_counts()
# ax = sns.barplot(gender_cnt)
# ax.bar_label(ax.containers[0])


edu_lvl = df["Education_Level"].value_counts()
ax = sns.barplot(edu_lvl)
ax.bar_label(ax.containers[0])

In [ ]:
# Analyze Income

sns.histplot(
    data = df, 
    x = "Applicant_Income",
    bins = 20
)

In [ ]:
sns.histplot(
    data = df, 
    x = "Coapplicant_Income",
    bins = 20
)

In [ ]:
# Outliers - Box Plot
sns.boxplot(
    data = df,
    x="Loan_Approved",
    y="Applicant_Income"
)

In [ ]:
fig, axes = plt.subplots(3,2, 
                         figsize=(12, 8))
sns.boxplot(ax=axes[0, 0], data=df, x="Loan_Approved", y="Applicant_Income")
sns.boxplot(ax=axes[0, 1], data=df, x="Loan_Approved", y="Credit_Score")
sns.boxplot(ax=axes[1, 0], data=df, x="Loan_Approved", y="DTI_Ratio")
sns.boxplot(ax=axes[1, 1], data=df, x="Loan_Approved", y="Savings")
sns.boxplot(ax=axes[2, 0], data=df, x="Loan_Approved", y="Age")
sns.boxplot(ax=axes[2, 1], data=df, x="Loan_Approved", y="Loan_Amount")

plt.tight_layout()

In [ ]:
# Credit Score with Loan Approved

sns.histplot(
    data = df,
    x="Credit_Score",
    hue="Loan_Approved",
    bins=20,
    multiple="dodge"
)

In [ ]:
# Remove Applicant's Id

df = df.drop("Applicant_ID", axis=1)

# Encoding

In [49]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Applicant_Income                 1000 non-null   float64
 1   Coapplicant_Income               1000 non-null   float64
 2   Age                              1000 non-null   float64
 3   Dependents                       1000 non-null   float64
 4   Credit_Score                     1000 non-null   float64
 5   Existing_Loans                   1000 non-null   float64
 6   DTI_Ratio                        1000 non-null   float64
 7   Savings                          1000 non-null   float64
 8   Collateral_Value                 1000 non-null   float64
 9   Loan_Amount                      1000 non-null   float64
 10  Loan_Term                        1000 non-null   float64
 11  Education_Level                  1000 non-null   int64
 12  Loan_Approved                    1000 non-null   int64
 13  Employment_Status_Salaried       1000 non-null   float64
 14  Employment_Status_Self-employed  1000 non-null   float64
 15  Employment_Status_Unemployed     1000 non-null   float64
 16  Marital_Status_Single            1000 non-null   float64
 17  Loan_Purpose_Car                 1000 non-null   float64
 18  Loan_Purpose_Education           1000 non-null   float64
 19  Loan_Purpose_Home                1000 non-null   float64
 20  Loan_Purpose_Personal            1000 non-null   float64
 21  Property_Area_Semiurban          1000 non-null   float64
 22  Property_Area_Urban              1000 non-null   float64
 23  Gender_Male                      1000 non-null   float64
 24  Employer_Category_Government     1000 non-null   float64
 25  Employer_Category_MNC            1000 non-null   float64
 26  Employer_Category_Private        1000 non-null   float64
 27  Employer_Category_Unemployed     1000 non-null   float64
 28  DTI_Ratio_sq                     1000 non-null   float64
 29  Credit_Score_sq                  1000 non-null   float64
dtypes: float64(28), int64(2)
memory usage: 234.5 KB

In [50]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le = LabelEncoder()
df["Education_Level"] = le.fit_transform(df["Education_Level"])
df["Loan_Approved"] = le.fit_transform(df["Loan_Approved"])

In [51]:
cols = ["Employment_Status", "Marital_Status", "Loan_Purpose", "Property_Area", "Gender", "Employer_Category"]

ohe = OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore")
encoded = ohe.fit_transform(df[cols])

encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(cols), index=df.index)

df = pd.concat([df.drop(columns = cols),encoded_df], axis=1)

KeyError: "None of [Index(['Employment_Status', 'Marital_Status', 'Loan_Purpose', 'Property_Area',\n       'Gender', 'Employer_Category'],\n      dtype='object')] are in the [columns]"

In [ ]:
df.head()
df.info()

# Correlation HeatMap

In [ ]:
nums_cols = df.select_dtypes(include="number")
corr_matrix = nums_cols.corr()

plt.figure(figsize =(15,8))
sns.heatmap(
    corr_matrix,
    annot =True,
    fmt = " .2f",
    cmap = "coolwarm"
)

In [ ]:
nums_cols.corr()["Loan_Approved"].sort_values(ascending=False)

# Train-Test-Split

In [ ]:
X = df.drop("Loan_Approved", axis=1)
y = df["Loan_Approved"]

In [ ]:
X.head()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [ ]:
X_test.head()

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_test_scaled

# Train & Evaluate Models

In [ ]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 


log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

y_pred = log_model.predict(X_test_scaled)

# Evaluation
print("Logistic Regression")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion: ", confusion_matrix(y_test, y_pred))

In [ ]:
# kNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 


knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

y_pred = knn_model.predict(X_test_scaled)

# Evaluation
print("kNN Classifier")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion: ", confusion_matrix(y_test, y_pred))

In [ ]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 


nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

y_pred = nb_model.predict(X_test_scaled)

# Evaluation
print("GaussianNB")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion: ", confusion_matrix(y_test, y_pred))

# Best Model on the basis of Precision => Naive Bayes

# Feature Engineering

In [52]:
df["DTI_Ratio_sq"] = df["DTI_Ratio"] ** 2
df["Credit_Score_sq"] = df["Credit_Score"] ** 2

# df["Applicant_Income_log"] = np.log1p(df["Applicant_Income"])


X = df.drop(columns=["Loan_Approved", "Credit_Score", "DTI_Ratio"])
y = df["Loan_Approved"]

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

# Scaling 
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [53]:
X_train.head()

,Applicant_Income,Coapplicant_Income,Age,Dependents,Existing_Loans,Savings,Collateral_Value,Loan_Amount,Loan_Term,Education_Level,...,Loan_Purpose_Personal,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,DTI_Ratio_sq,Credit_Score_sq
29,5890.000000,8041.0,31.000000,0.0,0.000000,11906.0,8150.000000,29287.000000,12.0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0121,363609.000000
535,4779.000000,529.0,50.000000,0.0,0.000000,5369.0,5430.000000,14786.000000,72.0,1,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0441,376996.000000
695,10852.571579,8927.0,36.000000,0.0,4.000000,3186.0,24802.792632,20522.825263,48.0,1,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0484,341056.000000
557,2384.000000,2113.0,39.971579,1.0,4.000000,11882.0,48542.000000,13312.000000,24.0,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.1156,527076.000000
836,5228.000000,5249.0,42.000000,1.0,1.950526,17669.0,24802.792632,13906.000000,84.0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0324,457021.542187

In [54]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 


log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

y_pred = log_model.predict(X_test_scaled)

# Evaluation
print("Logistic Regression")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion: ", confusion_matrix(y_test, y_pred))

Logistic Regression
Precision:  0.7903225806451613
Recall Score:  0.8032786885245902
F1_Score:  0.7967479674796748
Accuracy:  0.875
Confusion:  [[126  13]
 [ 12  49]]

In [55]:
# kNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 


knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

y_pred = knn_model.predict(X_test_scaled)

# Evaluation
print("kNN Classifier")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion: ", confusion_matrix(y_test, y_pred))

kNN Classifier
Precision:  0.62
Recall Score:  0.5081967213114754
F1_Score:  0.5585585585585585
Accuracy:  0.755
Confusion:  [[120  19]
 [ 30  31]]

In [56]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 


nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

y_pred = nb_model.predict(X_test_scaled)

# Evaluation
print("GaussianNB")
print("Precision: ", precision_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("F1_Score: ", f1_score(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion: ", confusion_matrix(y_test, y_pred))

GaussianNB
Precision:  0.7833333333333333
Recall Score:  0.7704918032786885
F1_Score:  0.7768595041322314
Accuracy:  0.865
Confusion:  [[126  13]
 [ 14  47]]